#!/bin/bash

fichier=`zenity --file-selection --title "Fichier d'où extraire :"`
save=`zenity --file-selection --save --title "Fichier où sauvegarder les mots de passe :"`

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo $line | cut -d':' -f2 >> "$save"
done < "$fichier"

zenity --info --title "Extract Passwords from List" --text "Extraction complète"

exit 0
