#!/bin/bash

os=`cat /etc/issue.net | cut -d" " -f1`

if [ "$os" == "Debian" ]; then
	debaj="user_pref(\"extensions.update.enabled\", \"true\");
user_pref(\"intl.locale.matchOS\", \"true\");
user_pref(\"browser.shell.checkDefaultBrowser\", \"false\");
user_pref(\"media.gmp-manager.url.override\", \"data:text/plain,\");
user_pref(\"media.gmp-gmpopenh264.enabled\", \"false\");
user_pref(\"browser.newtabpage.enhanced\", \"false\");
user_pref(\"datareporting.healthreport.uploadEnabled\", \"false\");"
else
	debaj=""
fi

cd $HOME/.mozilla/firefox

prefjs=`find . -name "prefs.js"`

absolu=$(readlink -f $(dirname $prefjs))

touch $absolu/user.js

echo "// Mode parano 
user_pref(\"media.peerconnection.enabled\", \"false\");
user_pref(\"browser.cache.disk.enable\", \"false\");
user_pref(\"browser.cache.disk_cache_ssl\", \"false\");
user_pref(\"browser.cache.offline.enable\", \"false\");
user_pref(\"browser.cache.memory.capacity\", \"8192\");
user_pref(\"browser.cache.disk.capacity\", \"15000\");
user_pref(\"browser.cache.disk.smart_size.enabled\", \"false\");
user_pref(\"browser.cache.disk.smart_size.first_run\", \"false\");
user_pref(\"browser.cache.offline.capacity\", \"0\");
user_pref(\"dom.storage.enabled\", \"false\");
user_pref(\"dom.indexedDB.enabled\", \"false\");
user_pref(\"dom.battery.enabled\", \"false\");
user_pref(\"browser.search.suggest.enabled\", \"false\");
user_pref(\"browser.sessionstore.resume_from_crash\", \"false\");
user_pref(\"geo.enabled\", \"false\");
user_pref(\"keyword.enabled\", \"false\");
user_pref(\"network.dns.disablePrefetch\", \"true\");
user_pref(\"network.dns.disableIPv6\", \"true\");
user_pref(\"dom.disable_window_open_feature.menubar\", \"true\");
user_pref(\"dom.disable_window_open_feature.personalbar\", \"true\");
user_pref(\"dom.disable_window_open_feature.scrollbars\", \"true\");
user_pref(\"dom.disable_window_open_feature.toolbar\", \"true\");
user_pref(\"browser.identity.ssl_domain_display\", \"1\");
user_pref(\"browser.urlbar.autocomplete.enabled\", \"false\");
user_pref(\"browser.urlbar.trimURL\", \"false\");
user_pref(\"network.http.sendSecureXSiteReferrer\", \"false\");
user_pref(\"network.http.spdy.enabled\", \"false\");
user_pref(\"security.enable_tls_session_tickets\", \"false\");
user_pref(\"extensions.blocklist.enabled\", \"false\");
user_pref(\"webgl.disabled\", \"true\");
user_pref(\"plugins.click_to_play\", \"true\");
user_pref(\"security.ssl.enable_false_start\", \"true\");
user_pref(\"general.useragent.override\", \"Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0\");
user_pref(\"general.appname.override\", \"Netscape\");
user_pref(\"general.appversion.override\", \"5.0\");
user_pref(\"general.oscpu.override\", \"Windows NT 6.1\");
user_pref(\"general.platform.override\", \"Win32\");
user_pref(\"general.productSub.override\", \"20100101\");
user_pref(\"general.buildID.override\", \"0\");
user_pref(\"general.useragent.vendor\", \"\");
user_pref(\"general.useragent.vendorSub\", \"\");
user_pref(\"intl.accept_languages\", \"en-us,en;q=0.5\");
user_pref(\"network.http.accept.default\", \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\");
user_pref(\"network.http.accept-encoding\", \"gzip, deflate\");
user_pref(\"media.peerconnection.enabled\", \"false\");
user_pref(\"network.cookie.cookieBehavior\", \"3\");
user_pref(\"network.cookie.lifetimePolicy\", \"2\");
user_pref(\"network.cookie.thirdparty.sessionOnly\", \"true\");
user_pref(\"privacy.trackingprotection.enabled\", \"true\");
user_pref(\"datareporting.healthreport.service.enabled\", \"false\");
user_pref(\"datareporting.healthreport.service.firstRun\", \"false\");
user_pref(\"datareporting.healthreport.about.reportUrl\", \"\");
user_pref(\"datareporting.healthreport.about.reportUrlUnified\", \"\");
user_pref(\"datareporting.healthreport.documentServerURI\", \"\");
user_pref(\"datareporting.healthreport.infoURL\", \"\");
user_pref(\"browser.startup.homepage\", \"http://whatismyipaddress.com|https://www.dnsleaktest.com/\");
user_pref(\"capability.policy.maonoscript.sites\", \"addons.mozilla.org about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:pocket-saved about:pocket-signup about:preferences about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: mediasource: moz-extension: moz-safe-about: resource:\");
user_pref(\"startup.homepage_welcome_url\", \"\");
user_pref(\"startup.homepage_welcome_url.additional\", \"\");
user_pref(\"browser.aboutHomeSnippets.updateUrl\", \"\");
user_pref(\"security.ssl.errorReporting.automatic\", \"false\");
user_pref(\"security.ssl.errorReporting.enabled\", \"false\");
user_pref(\"security.ssl.errorReporting.url\", \"\");
user_pref(\"browser.safebrowsing.reportMalwareMistakeURL\", \"\");
user_pref(\"browser.safebrowsing.reportPhishMistakeURL\", \"\");
user_pref(\"browser.safebrowsing.reportPhishURL\", \"\");
user_pref(\"geo.wifi.uri\", \"\");
user_pref(\"network.http.sendRefererHeader\", \"0\");
$debaj" > $absolu/user.js

zenity --info --text "Les améliorations prendront effet au redémarrage du naviguateur ;)"

exit 0
